### PR TITLE
Further documentation improvements

### PR DESCRIPTION
**Pull request by grunweg**
I made a few further improvements to the doc comments, similar in spirit to #110.

I don't know how to get rid of the merge commit (github added that for me). Feel free to rebase for me and remove it.

### CODE REVIEW

**Comment by grunweg** [comment]
Oops, wrong branch. Will re-open with the right commits.

**Comment by grunweg** [comment]
Actually, no: I thought I had already submitted this, but it turns out I never did. Oh well --- here you are.

**Comment by pksunkara** [comment]
Needs correction.

**Comment by grunweg** [comment]
Superseeded by #119; the additional commits are duplicate with #121. Closing.

**Pull request closed without merging**
