### PR TITLE
Upgrade to terminal_size v0.2

### PR DESCRIPTION
**Pull request by benesch**

### CODE REVIEW

**Comment by pksunkara** [comment]
That version uses different dependencies to libc and winapi. So, doing this now without changing our own dependencies just adds more dependencies to compile time for not much benefit.

**Comment by benesch** [comment]
Will you accept a revision that does the version upgrade of terminal_size
and also ports console over to rustix and windows-sys? If so please reopen.

**Comment by benesch** [comment]
Thanks! I'll take a look at this when I can.

**Comment by benesch** [comment]
Ah, never mind. I'm afraid I just won't have the time.

**Pull request closed without merging**
