### PR TITLE
Bump MSRV to 1.48.0

### PR DESCRIPTION
**Pull request by messense**
Per https://github.com/console-rs/console/issues/134#issuecomment-1307391821

Closes #139

### CODE REVIEW

**Comment by messense** [comment]
The macOS test failure should be easy to fix by use an old version of Xcode, wasm32-wasi build failure is caused by https://github.com/rust-lang/rust/issues/103306 which will be stabilized in [1.67.0](https://github.com/rust-lang/rust/pull/103734), we can switch to nightly for now.

I'm not sure how to deal with the `wasm32-unknown-unknown` build failure.

**Comment by LingMan** [comment]
`wasm32-unknown-unknown` support for errno was discussed in https://github.com/lambda-fairy/rust-errno/issues/21.

**Comment by mitsuhiko** [comment]
Does `terminal_size` actually work on WASI? Because if all it does is have some hardcoded fallback then the sanest option would probably be to just stop using that crate for WASI.

**Comment by mitsuhiko** [comment]
Now that I looked closer at this I'm not a huge fan of the fact that `terminal_size` 0.2 pulls in that many dependencies for what should be a rather simple task. I wonder if it wouldn't be better to switch to manual implementations again rather than using `terminal_size`.

**Comment by messense** [comment]
> Does `terminal_size` actually work on WASI?

@eminence any idea?

**Comment by eminence** [comment]
> > Does terminal_size actually work on WASI?
>
> @eminence any idea?

No, `terminal_size` doesn't target WASI at all.  I'm not sure if WASI today has any interfaces to get things like "terminal size".  @sunfishcode -- Do you know if this is something that WASI might support in the future?

@messense I'm now thinking that `terminal_size` should just return `None` on WASI targets.  Would that be useful for you here?

**Comment by sunfishcode** [comment]
@eminence That's right; WASI does not currently have APIs for returning the terminal size. It may in the future though.

**Comment by eminence** [comment]
The code is really very small, so I think you should be able to very easily drop `terminal_size` and just include the relevant code directly in `console`.

**Pull request merged**
